### ISSUE TITLE
As an owner or logistics person, I want to view a list of products of a collection with their respective names, stock statuses, and pictures, so I can quickly identify the products available in the system.

### ISSUE THREAD

**Issue by cookietriestoprogram** [cookietriestoprogram/abstrak#1]
Acceptance Criteria:

1. When searching for a product by name, the list should display only the matching products.
2. The stock status of each product should be clearly indicated as available, low stock, or out of stock.
3. If a product has no image available, a default placeholder image should be displayed instead.
4. Clicking on a product name should navigate to its detailed view, displaying comprehensive information including description, price, and any variations.
5. Verify that the product list gracefully handles scenarios where there are no products available or when there is an error fetching product information.
6. Add two products with identical names and ensure both are listed correctly without overlap or duplication.
7. Populate the system with a significant number of products (e.g., 1000+) and assess the responsiveness and accuracy of the search feature.
8. Validate the behavior when there are products with special characters or symbols in their names.
9. Test the handling of inactive or discontinued products.
10. Evaluate the display of long product names.
11. Validate that the product images are of high resolution and correctly aligned with their respective listings, ensuring a visually appealing display.

![Image](https://github.com/cookietriestoprogram/abstrak/assets/96109976/ebe0c583-0bd8-40b6-a6c4-271982925078)

**Comment by cookietriestoprogram** [comment]
Tasks:

[] Create dummy data
[] Design a frontend for an entry
[] Fetch data for a specific collection from the database
[] Identify products within the collection.
[] Categorize low-stock from out of stock
[] Pass the data from frontend to backend

**Comment by cookietriestoprogram** [comment]
Frontend
- [ ] Design a frontend for an entry
- [ ] Design the frontend grid style

Backend

- [ ] Create dummy products in the database
- [ ] Fetch data for a specific collection from the database
- [ ] Identify products within the collection.
- [ ] Categorize low-stock from out of stock
- [ ] Pass the data from frontend to backend

**Comment by AhStayinAlive** [comment]
-[nkascac
]

**Comment by AhStayinAlive** [comment]
- [ ] saxbajkxbas

**Comment by pngnyume** [comment]
@cookietriestoprogram 

[Sprint 2] Revisions:
- [ ] Revise to scroll down

**Comment by AhStayinAlive** [comment]
Front-end:
- [ ] Design the page where the user can see all products under the collection.
- [ ] Scroll down to further see the products.
- [ ] Show to picture, name, and current stock of the product.
- [ ] Create a color-coding system on the stock.

Back-end:
- [ ] Fetch the latest data of products of the collection.
- [ ] Aggregate the stock.
- [ ] Dynamically change the color of the status depending on the number of status.
