### ISSUE TITLE
As an owner or logistics person, I want to see the sales report of each product listed, allowing me to assess the profitability of each item.

### ISSUE THREAD

**Issue by cookietriestoprogram** [cookietriestoprogram/abstrak#16]
1. Given that I am logged in as an owner, when I access the product dashboard, then I should have the option to view the sales report for each product.
2. The sales report should include metrics such as total revenue, total units sold, and profit margin.
3. The report should be up-to-date.
4. Ensure the report is generated efficiently and that calculations are accurate, with validation against known data points.

Acceptance Criteria:
- [x] The sales report must accurately reflect all sales transactions for each product, matching the transaction records in the database.
- [x] The sales report must update in real-time to include new transactions immediately after they are recorded.
- [x]  The sales report should display the 
Quantity Sold
Total Sales Amount
Cost Price
Selling Price
Total Cost
Gross Profit
Return Rate
Profit Margin (gross profit/total sales amount) * 100
Overall trend (sales over time, profit over time)

Test: 
- [ ] Compare the sales data in the report with the raw transaction data from the database for consistency. This can be done by generating the report and verifying each entry against a known dataset in the test environment.
- [ ] Generate a sales report and verify that each required metric is present and correctly calculated by comparing them against a known dataset and manual calculations.

**Comment by AhStayinAlive** [comment]
Front End
- [ ] Design the interface
- [ ] Display the necessary information of the product. Use graph to display statistics.
- [ ] Provide loading indicators while data is being fetched.
- Add a reload button to give option to the user to manually reload.

Back-end:
- Fetch the latest data from the database.
- Implement data aggregation logic to calculate total revenue, total units sold, and profit margin.
- Ensure calculations are correct.
