### ISSUE TITLE
As an owner or logistics person, I want to view detailed information about each order, including the list of items ordered, quantity, price, and total amount, allowing me to review the contents of each transaction.

### ISSUE THREAD

**Issue by cookietriestoprogram** [cookietriestoprogram/abstrak#18]
1. Given that I click on an order from the list, then I should be directed to a page displaying detailed information about the selected order.
2. The order details should include the list of items ordered, quantity, price, and total amount.
3. The information should be presented in a clear and organized manner.

![Image](https://github.com/cookietriestoprogram/abstrak/assets/69201574/3f64bf56-3b99-4a7e-8c6c-96483859559d)

Acceptance Criteria: 

- [ ] The order details view should display all relevant information that Wix allows to export.

Test: 

- [ ] Compare the data exported from Wix with the information displayed in the order details view.

**Comment by AhStayinAlive** [comment]
Front-end
- [ ] Design the order page layout,
- [ ] Display the necessary information about the order.
- [ ] Add a button where the admin can change the status of the product.

Back-end:
- [ ] Fetch the data from database.
- [ ] Update the database if the status is changed
